# Generated by Django 3.1.5 on 2021-01-17 16:02

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('transports_will_buy', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='ManufacturerCountry',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('man_country', models.CharField(max_length=30, verbose_name='Արտադրման երկիր')),
            ],
        ),
        migrations.AlterModelOptions(
            name='regionchildmodel',
            options={'verbose_name': 'Տարածաշրջան-Raion', 'verbose_name_plural': 'Տարածաշրջան-Raion'},
        ),
    ]
