# Generated by Django 3.1.5 on 2021-01-17 16:06

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('transports_will_buy', '0002_auto_20210117_1602'),
    ]

    operations = [
        migrations.AddField(
            model_name='transportfieldsmodel',
            name='millage_int',
            field=models.IntegerField(default=None, null=True, verbose_name='Վազք'),
        ),
    ]
