# Generated by Django 3.1.5 on 2021-01-15 21:56

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('transport_parts', '0001_initial'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='transportfieldsmodel',
            name='photo_main',
        ),
        migrations.AddField(
            model_name='transportfieldsmodel',
            name='desc_language',
            field=models.CharField(choices=[('ARM', 'Am'), ('RUS', 'Ru'), ('EN', 'En')], default='ARM', max_length=50),
        ),
        migrations.AddField(
            model_name='transportfieldsmodel',
            name='photo_5',
            field=models.ImageField(blank=True, upload_to='photos/transport/%Y/%m/%d/'),
        ),
        migrations.AlterField(
            model_name='transportfieldsmodel',
            name='country',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='transport_parts.countrymodel'),
        ),
        migrations.AlterField(
            model_name='transportfieldsmodel',
            name='created_at',
            field=models.DateTimeField(auto_now=True, null=True, verbose_name="don't touch"),
        ),
        migrations.AlterField(
            model_name='transportfieldsmodel',
            name='description',
            field=models.TextField(blank=True, null=True, verbose_name='Նկարագրել'),
        ),
        migrations.AlterField(
            model_name='transportfieldsmodel',
            name='exchange',
            field=models.BooleanField(blank=True, default=False, null=True, verbose_name='Փոխանակում'),
        ),
        migrations.AlterField(
            model_name='transportfieldsmodel',
            name='mileage',
            field=models.CharField(choices=[('km', 'Km'), ('ml', 'Ml')], default='km', max_length=50, verbose_name='Վազք-type'),
        ),
    ]
