# Generated by Django 3.1.5 on 2021-01-17 17:07

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('transports', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Caliber',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('caliber_type', models.CharField(max_length=33, verbose_name='Տրամաչափ')),
            ],
            options={
                'verbose_name': 'Անվահեծի տրամաչափ',
                'verbose_name_plural': 'Անվահեծերի տրամաչափ',
            },
        ),
        migrations.CreateModel(
            name='Color',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('color', models.CharField(max_length=40, verbose_name='Գույն')),
            ],
            options={
                'verbose_name': 'Գույն',
                'verbose_name_plural': 'Գույներ',
            },
        ),
        migrations.CreateModel(
            name='ContactCode',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('code', models.CharField(max_length=12)),
            ],
            options={
                'verbose_name': 'Երկրի կոդ',
                'verbose_name_plural': 'Երկրների կոդեր',
            },
        ),
        migrations.CreateModel(
            name='CountryModel',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('country_name', models.CharField(max_length=32, verbose_name='Երկիր')),
            ],
            options={
                'verbose_name': 'Երկիր',
                'verbose_name_plural': 'Երկիր',
            },
        ),
        migrations.CreateModel(
            name='HolesQty',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('qty', models.PositiveIntegerField(verbose_name='Անցքերի քանակը')),
            ],
            options={
                'verbose_name': 'Անցքերի քանակը',
                'verbose_name_plural': 'Անցքերի քանակը',
            },
        ),
        migrations.CreateModel(
            name='RegionChildModel',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('region_child', models.CharField(max_length=55, verbose_name='Տարածաշրջան')),
            ],
            options={
                'verbose_name': 'Տարածաշրջան-Raion',
                'verbose_name_plural': 'Տարածաշրջան-Raion',
            },
        ),
        migrations.CreateModel(
            name='RegionModel',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('region_name', models.CharField(max_length=32)),
            ],
            options={
                'verbose_name': 'Տարածաշրջան',
                'verbose_name_plural': 'Տարածաշրջան',
            },
        ),
        migrations.CreateModel(
            name='Wheel',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('The_size_of_the_wheel_holes', models.PositiveIntegerField(verbose_name='Անվահեծի անցքերի չափ')),
                ('new', models.BooleanField(default=False, verbose_name='Նոր')),
                ('used', models.BooleanField(default=False, verbose_name='Օգտագործված')),
                ('qty', models.PositiveIntegerField(verbose_name='Քանակ')),
                ('photo_1', models.ImageField(blank=True, upload_to='photos/transport/%Y/%m/%d/')),
                ('photo_2', models.ImageField(blank=True, upload_to='photos/transport/%Y/%m/%d/')),
                ('photo_3', models.ImageField(blank=True, upload_to='photos/transport/%Y/%m/%d/')),
                ('photo_4', models.ImageField(blank=True, upload_to='photos/transport/%Y/%m/%d/')),
                ('photo_5', models.ImageField(blank=True, upload_to='photos/transport/%Y/%m/%d/')),
                ('price', models.DecimalField(decimal_places=2, max_digits=19, verbose_name='Գին')),
                ('price_per_unit', models.DecimalField(decimal_places=2, max_digits=19, verbose_name='Գինը հատի դեպքում')),
                ('price_type', models.CharField(choices=[('AMD', 'Amd'), ('RUB', 'Ru'), ('USD', 'Usd'), ('EUR', 'Eur')], default='AMD', max_length=50)),
                ('desc_language', models.CharField(choices=[('ARM', 'Am'), ('RUS', 'Ru'), ('EN', 'En')], default='ARM', max_length=50)),
                ('description', models.TextField(blank=True, null=True, verbose_name='Նկարագրել')),
                ('hashtag', models.CharField(blank=True, max_length=255, null=True, verbose_name='Գաղտնի որոնում')),
                ('contact', models.CharField(max_length=33, verbose_name='Կոնտակտ')),
                ('contact_type', models.CharField(choices=[('whatsapp', 'Whatsapp'), ('viber', 'Viber'), ('telegram', 'Telegram'), ('zangi', 'Zangi')], max_length=32, verbose_name='Կոնտակտ_type')),
                ('dealer', models.BooleanField(default=False, verbose_name='Դիլլեր')),
                ('created_at', models.DateTimeField(auto_now=True, verbose_name="don't touch")),
                ('exchange', models.BooleanField(default=False, verbose_name='Փոխանակում')),
                ('caliber', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='WHEELS.caliber')),
                ('car_brand', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='transports.carbrand')),
                ('car_model', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='transports.carmodel')),
                ('clearance', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='transports.clearance')),
                ('color', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='WHEELS.color')),
                ('contact_code', models.ForeignKey(default=None, on_delete=django.db.models.deletion.CASCADE, to='WHEELS.contactcode')),
                ('country', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='WHEELS.countrymodel')),
                ('holes_qty', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='WHEELS.holesqty')),
                ('product_year', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, to='transports.productyear')),
                ('region_child', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='WHEELS.regionchildmodel')),
                ('region_name', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='WHEELS.regionmodel')),
            ],
            options={
                'verbose_name': 'Անվահեծ',
                'verbose_name_plural': 'Անվահեծեր',
            },
        ),
        migrations.AddField(
            model_name='regionchildmodel',
            name='region',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='WHEELS.regionmodel', verbose_name='Տարածաշրջան'),
        ),
        migrations.AddField(
            model_name='contactcode',
            name='cod_country',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='WHEELS.countrymodel'),
        ),
    ]
