# Generated by Django 3.1.5 on 2021-01-17 17:07

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='CarBody',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('car_body', models.CharField(max_length=32, verbose_name='Թափքի տեսակ')),
            ],
            options={
                'verbose_name': 'Թափքի տեսակ',
                'verbose_name_plural': 'Թափքի տեսակ',
            },
        ),
        migrations.CreateModel(
            name='CarBrand',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('brand_name', models.CharField(max_length=50, verbose_name='Մակնիշ')),
            ],
            options={
                'verbose_name': 'Մակնիշ',
                'verbose_name_plural': 'Մակնիշ',
            },
        ),
        migrations.CreateModel(
            name='CarModel',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('model_name', models.CharField(max_length=30, verbose_name='Մոդել')),
                ('category', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='transports.carbrand')),
            ],
            options={
                'verbose_name': 'Մոդել',
                'verbose_name_plural': 'Մոդել',
            },
        ),
        migrations.CreateModel(
            name='Clearance',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('clearance', models.CharField(max_length=32, verbose_name='Մաքսազերծված է')),
            ],
            options={
                'verbose_name': 'Մաքսազերծված է',
                'verbose_name_plural': 'Մաքսազերծված է',
            },
        ),
        migrations.CreateModel(
            name='Color',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('color', models.CharField(max_length=32, verbose_name='Գույն')),
            ],
            options={
                'verbose_name': 'Գույն',
                'verbose_name_plural': 'Գույն',
            },
        ),
        migrations.CreateModel(
            name='ContactCode',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('code', models.CharField(max_length=12)),
            ],
            options={
                'verbose_name': 'Երկրի կոդ',
                'verbose_name_plural': 'Երկրների կոդեր',
            },
        ),
        migrations.CreateModel(
            name='CountryModel',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('country_name', models.CharField(max_length=32, verbose_name='Երկիր')),
            ],
            options={
                'verbose_name': 'Երկիր',
                'verbose_name_plural': 'Երկիր',
            },
        ),
        migrations.CreateModel(
            name='DriveUnit',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('drive_unit', models.CharField(max_length=32, verbose_name='Քարշակ')),
            ],
            options={
                'verbose_name': 'Քարշակ',
                'verbose_name_plural': 'Քարշակ',
            },
        ),
        migrations.CreateModel(
            name='Fuel',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('fuel_type', models.CharField(max_length=32, verbose_name='Վառելիք')),
            ],
            options={
                'verbose_name': 'Վառելիք',
                'verbose_name_plural': 'Վառելիք',
            },
        ),
        migrations.CreateModel(
            name='ManufacturerCountry',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('man_country', models.CharField(max_length=30, verbose_name='Արտադրման երկիր')),
            ],
            options={
                'verbose_name': 'Արտադրման երկիր',
                'verbose_name_plural': 'Արտադրման երկիր',
            },
        ),
        migrations.CreateModel(
            name='Motor',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('motor', models.CharField(max_length=32, verbose_name='Շարժիչի ծավա')),
            ],
            options={
                'verbose_name': 'Շարժիչի ծավալ',
                'verbose_name_plural': 'Շարժիչի ծավալ',
            },
        ),
        migrations.CreateModel(
            name='ProductYear',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('product_year', models.CharField(max_length=32, verbose_name='Տարի')),
            ],
            options={
                'verbose_name': 'Տարի',
                'verbose_name_plural': 'Տարի',
            },
        ),
        migrations.CreateModel(
            name='RegionChildModel',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('region_child', models.CharField(max_length=55, verbose_name='Տարածաշրջան')),
            ],
            options={
                'verbose_name': 'Տարածաշրջան-Raion',
                'verbose_name_plural': 'Տարածաշրջան-Raion',
            },
        ),
        migrations.CreateModel(
            name='RegionModel',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('region_name', models.CharField(max_length=32)),
            ],
            options={
                'verbose_name': 'Տարածաշրջան',
                'verbose_name_plural': 'Տարածաշրջան',
            },
        ),
        migrations.CreateModel(
            name='Steering',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('steering', models.CharField(max_length=32, verbose_name='Ղեկ')),
            ],
            options={
                'verbose_name': 'Ղեկ',
                'verbose_name_plural': 'Ղեկ',
            },
        ),
        migrations.CreateModel(
            name='Transmission',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('transmission', models.CharField(max_length=32, verbose_name='Փոխանցման տուփ')),
            ],
            options={
                'verbose_name': 'Փոխանցման տուփ',
                'verbose_name_plural': 'Փոխանցման տուփ',
            },
        ),
        migrations.CreateModel(
            name='TransportFieldsModel',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('vin_code', models.CharField(blank=True, max_length=32, null=True, unique=True, verbose_name='Vin Code')),
                ('show_vin_code', models.BooleanField(default=True)),
                ('new', models.BooleanField(default=False, verbose_name='Նոր')),
                ('used', models.BooleanField(default=False, verbose_name='Օգտագործված')),
                ('horse_power', models.IntegerField(verbose_name='Ձիաուժ')),
                ('millage_int', models.IntegerField(verbose_name='Վազք')),
                ('mileage', models.CharField(choices=[('km', 'Km'), ('ml', 'Ml')], default='km', max_length=50, verbose_name='Վազք-type')),
                ('photo_main', models.ImageField(upload_to='photos/transport/%Y/%m/%d/')),
                ('photo_1', models.ImageField(blank=True, upload_to='photos/transport/%Y/%m/%d/')),
                ('photo_2', models.ImageField(blank=True, upload_to='photos/transport/%Y/%m/%d/')),
                ('photo_3', models.ImageField(blank=True, upload_to='photos/transport/%Y/%m/%d/')),
                ('photo_4', models.ImageField(blank=True, upload_to='photos/transport/%Y/%m/%d/')),
                ('photo_5', models.ImageField(blank=True, upload_to='photos/transport/%Y/%m/%d/')),
                ('photo_6', models.ImageField(blank=True, upload_to='photos/transport/%Y/%m/%d/')),
                ('photo_7', models.ImageField(blank=True, upload_to='photos/transport/%Y/%m/%d/')),
                ('photo_8', models.ImageField(blank=True, upload_to='photos/transport/%Y/%m/%d/')),
                ('photo_9', models.ImageField(blank=True, upload_to='photos/transport/%Y/%m/%d/')),
                ('photo_10', models.ImageField(blank=True, upload_to='photos/transport/%Y/%m/%d/')),
                ('photo_11', models.ImageField(blank=True, upload_to='photos/transport/%Y/%m/%d/')),
                ('price', models.DecimalField(decimal_places=2, max_digits=19, verbose_name='Գին')),
                ('price_type', models.CharField(choices=[('AMD', 'Amd'), ('RUB', 'Ru'), ('USD', 'Usd'), ('EUR', 'Eur')], default='AMD', max_length=50)),
                ('desc_language', models.CharField(choices=[('ARM', 'Am'), ('RUS', 'Ru'), ('EN', 'En')], default='ARM', max_length=50)),
                ('description', models.TextField(blank=True, null=True, verbose_name='Նկարագրել')),
                ('hashtag', models.CharField(blank=True, max_length=255, verbose_name='Գաղտնի որոնում')),
                ('contact', models.CharField(max_length=33, verbose_name='Կոնտակտ')),
                ('contact_type', models.CharField(choices=[('whatsapp', 'Whatsapp'), ('viber', 'Viber'), ('telegram', 'Telegram'), ('zangi', 'Zangi')], max_length=32, verbose_name='Կոնտակտ_type')),
                ('exchange', models.BooleanField(default=False, verbose_name='Փոխանակում')),
                ('dealer', models.BooleanField(default=False, verbose_name='Դիլլեր')),
                ('created_at', models.DateTimeField(auto_now=True, null=True, verbose_name="don't touch")),
                ('brand', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='transports.carbrand')),
                ('car_body', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='transports.carbody')),
                ('car_model', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='transports.carmodel')),
                ('clearance', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='transports.clearance')),
                ('color', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='transports.color')),
                ('contact_code', models.ForeignKey(default=None, on_delete=django.db.models.deletion.CASCADE, to='transports.contactcode')),
                ('country', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='country_names', to='transports.countrymodel')),
                ('drive_unit', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='transports.driveunit')),
                ('fuel', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='transports.fuel')),
                ('man_country', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='transports.manufacturercountry')),
                ('motor', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='transports.motor')),
                ('product_year', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, to='transports.productyear')),
                ('region_child', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='transports.regionchildmodel')),
                ('region_name', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='transports.regionmodel')),
                ('steering', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='transports.steering')),
                ('transmission', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='transports.transmission')),
            ],
            options={
                'verbose_name': 'ՏՐԱՆՍՊՈՐՏ',
                'verbose_name_plural': 'ՏՐԱՆՍՊՈՐՏ',
            },
        ),
        migrations.AddField(
            model_name='regionchildmodel',
            name='region',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='transports.regionmodel', verbose_name='Տարածաշրջան'),
        ),
        migrations.AddField(
            model_name='contactcode',
            name='cod_country',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='transports.countrymodel'),
        ),
    ]
