# Generated by Django 3.1.5 on 2021-01-16 11:06

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('transports', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='ContactCode',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('code', models.CharField(max_length=12)),
                ('cod_country', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='transports.countrymodel')),
            ],
        ),
    ]
