# Generated by Django 3.1.5 on 2021-01-17 11:25

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('transports', '0004_auto_20210117_1116'),
    ]

    operations = [
        migrations.AlterField(
            model_name='transportfieldsmodel',
            name='country',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='country_names', to='transports.countrymodel'),
        ),
    ]
